config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :public_recipes, only: %i[index]
  resources :general_shopping_lists, only: %i[index]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  resources :users, only: %i[index show] do
    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index new create show destroy] do
      resources :recipe_foods, only: %i[new create]
    end
  end

  root to: 'users#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipes_foods

  validates :name, presence: true
  validates :user, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @recipes = Recipe.includes(:user).where(user: @user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.includes(:user).find(params[:id])
    @recipe_foods = RecipeFood.includes(:food, :recipe).where(recipe_id: params[:id])
  end

  def create
    user = User.find(params[:user_id])
    created_recipe = Recipe.new(recipe_params)
    created_recipe.user_id = user.id

    if created_recipe.save
      flash[:notice] = 'Recipe created successfully.'
      redirect_to user_recipes_path(user, created_recipe)
    else
      flash[:error] = 'Recipe creation unsucessful!'
      @recipe = created_recipe
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path(@recipe.user, @recipe), notice: "Successfully deleted #{@recipe.name}."
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/index.html.erb
<% if user_signed_in? %>
<h1>Recipe lists :</h1>
<div>
<%= link_to "Create new recipe", new_user_recipe_path(@user, @recipes) %>

<%  @recipes.each do |recipe| %>
<p><%= link_to "Back to all users", users_path(recipe.user) %></p>
<p><%= link_to "Public recipes",  public_recipes_path(recipe) %></p>

<% if can? :read, recipe %>
<p><%= link_to "Recipe detail", user_recipe_path(recipe.user, recipe) %></p>
<% end %>

 <p>Recipe name: <%= recipe.name %>
 <p>description: <%= recipe.description %> 

 <% if can? :destroy, recipe %>
 <%= button_to "Delete recipe", user_recipe_path(recipe.user, recipe), method: :delete %>
<% end %>

<% end %>

<% end %>
</div>

app/views/recipes/new.html.erb
<h1>Create Recipe</h1>

<%= form_with model: @recipe, url: user_recipes_path, method: :post, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :preparation_time %>
  <%= f.number_field :preparation_time  %>
  <%= f.label :cooking_time %>
  <%= f.number_field :cooking_time  %>
  <%= f.label :description %>
  <%= f.text_area :description  %>
  <%= f.check_box :public  %>
  <%= f.label :public %>
  <%= f.submit "Save Recipe" %>
<% end %>

app/views/recipes/show.html.erb
<% if user_signed_in? %>
<h1>Recipe list detail :</h1>
<div >

<p><%= link_to "Back to all recipes", user_recipes_path(@recipe.user, @recipe) %></p>
 <p>Recipe name: <%= @recipe.name %> </p>
 <p>Preparation_time: <%= @recipe.preparation_time %> </p>
 <p>Cooking_time: <%= @recipe.cooking_time %> </p>
 <p>Recipe description: <%= @recipe.description %> </p>
 <p>Public: <%= @recipe.public %> </p>

 <% @recipe_foods.each do |recipe_food| %> 
    <p>Food-Name: <%= recipe_food.food.name %> </p>
    <p>RecipeFood_Quantity: <%= recipe_food.quantity %> </p>
    <p>Price of food: $<%= recipe_food.food.price %> </p>
    <% end %>

<% if @recipe.user == current_user %>
  <div >
     <%= link_to "Create New food", new_user_food_path(@recipe.user, @recipe.recipe_foods) %>
     <%= link_to "Ingredients", new_user_recipe_recipe_food_path(@recipe.user, @recipe, @recipe.recipe_foods) %>
  </div>
  <% end %>

<% end %>

</div>