config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :public_recipes, only: %i[index]
  resources :general_shopping_lists, only: %i[index]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  resources :users, only: %i[index show] do
    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index new create show destroy] do
      resources :recipe_foods, only: %i[new create]
    end
  end

  root to: 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods, foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %>
 <h1>Users :</h1>
 <h2>Welcome <%= current_user.name %>! </h2>
<%= link_to "See all recipes", user_recipes_path(current_user, current_user.recipes) %>
<%= link_to "See all foods", user_foods_path(current_user, current_user.foods) %>
<%= link_to "See all shopping lists", general_shopping_lists_path %>
<%= link_to "Public recipes", public_recipes_path(current_user.recipes) %>
<% end %>