config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :public_recipes, only: %i[index]
  resources :general_shopping_lists, only: %i[index]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  resources :users, only: %i[index show] do
    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index new create show destroy] do
      resources :recipe_foods, only: %i[new create]
    end
  end

  root to: 'users#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'food_id', dependent: :destroy
  has_many :recipes, through: :recipes_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :quantity, presence: true
  validates :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, only_integer: true }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  # GET /foods
  def index
    @user = User.find(params[:user_id])
    @foods = Food.includes(:user).where(user: @user.id)
  end

  # GET /new
  def new
    @food = Food.new # same as current_user.posts.build
  end

  # POST /foods
  def create
    user = User.find(params[:user_id])
    created_food = Food.new(food_params)
    created_food.user_id = user.id

    if created_food.save
      flash[:notice] = 'food created successfully.'
      redirect_to user_foods_path(user, created_food)
    else
      flash[:error] = 'food create unsucessful!'
      @food = created_food
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to user_foods_path(@food.user, @food), notice: "Successfully deleted #{@food.name}."
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<% if user_signed_in? %>
<h1>Food lists :</h1>
<div>

<% if @foods.empty? %>
<p>No food added yet!</p>
<% end %>

<p><%= link_to "Back to all users", users_path(@user) %></p>
<%= link_to "Create new food", new_user_food_path(@user, @foods) %>

<%  @foods.each do |food| %>
<p>Name of food: <%= food.name %>
<p>measurement_unit: <%= food.measurement_unit %>
<p>Price of food: <%= food.price %>
<p>Quantity of food: <%= food.quantity %>

<%= button_to "Delete food", user_food_path(food.user, food), method: :delete %>

<% end %>
<% end %>
</div>

app/views/foods/new.html.erb
<h1>Create new food</h1>

<%= form_with model: @food, url: user_foods_path, method: :post, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :measurement_unit %>
  <%= f.text_area :measurement_unit  %>
  <%= f.label :price %>
  <%= f.number_field :price  %>
  <%= f.label :quantity %>
  <%= f.number_field :quantity  %>
  <%= f.submit "Save food" %>
<% end %>