config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :public_recipes, only: %i[index]
  resources :general_shopping_lists, only: %i[index]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  resources :users, only: %i[index show] do
    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index new create show destroy] do
      resources :recipe_foods, only: %i[new create]
    end
  end

  root to: 'users#index'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'

  validates :food, presence: true
  validates :recipe, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @recipe_foods = RecipeFood.includes(:user).where(user: @user.id)
  end

  def new
    @recipe_food = RecipeFood.new # same as current_user.recipe_food.build
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    recipe = Recipe.find(params[:recipe_id])
    food = Food.where(user_id: current_user.id)
    created_recipe_food = RecipeFood.new(recipe_food_method)
    created_recipe_food.recipe_id = recipe.id
    created_recipe_food.food_id = food[0].id

    if created_recipe_food.save
      flash[:notice] = 'recipe_food created successfully.'
      redirect_to user_recipe_path(food[0].user, recipe)
    else
      flash[:error] = 'recipe_food creation unsucessful!'
      @recipe_food = created_recipe_food
      render :new
    end
  end

  private

  def recipe_food_method
    params.require(:recipe_food).permit(:quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path, method: :post do |form| %>
    <div >
       <%= form.number_field :quantity, Placeholder: "Quantity"%>
       <%= form.select :food, @foods&.map {|food| [food.name, food.id]} %>
       <%= form.submit %>
     </div>
<% end %>

app/views/recipe_foods/index.html.erb
<div >
<h2> Recipe Foods: </h2>
<p><% @recipe_foods.each do |recipe_food|
    <%= render partial: "recipes_food/index", locals: { recipe_food: recipe_food } %>
<% end %>
</p>
</div>

app/views/recipe_foods/new.html.erb
<h1>Create Recipe Foods: </h1>
<%= render "form", recipes_food: @recipe_food %>